#!/usr/bin/env expect
#
# Maintain whatis database on my custom man page directories.

package require Tcl 8.5

set tomake {}

foreach dir [split $env(MANPATH) ":"] {
    if {[file writable $dir]} {
        lappend tomake $dir
    }
}

exec /usr/libexec/makewhatis {*}$tomake
