#!/bin/sh
#
# upper left is typically for chat, or 'pa' tmux session; right hand
# xterms (re, ci) get tmux sessions and are where most development is
# done. lower left (vo) is either for extra development, or for
# connection the work tmux session. pa re ci vo are lojban numbers,
# which are nice and short
#shell='/usr/local/bin/zsh -l'
shell='/bin/ksh -l'
solitary "$HOME" /usr/X11R6/bin/xterm -geometry 80x34+0+0 -title pa -e $shell
solitary "$HOME" /usr/X11R6/bin/xterm -geometry 80x34-0+0 -title re -e 'tmn re'
solitary "$HOME" /usr/X11R6/bin/xterm -geometry 80x24-0-0 -title ci -e 'tmn ci'
solitary "$HOME" /usr/X11R6/bin/xterm -geometry 80x24+0-0 -title vo -e $shell
