#!/bin/sh
#
# upper left is typically for chat, or 'pa' tmux session; right hand
# xterms (re, ci) get tmux sessions and are where most development is
# done. lower left (vo) is either for extra development, or for
# connection the work tmux session. pa re ci vo are lojban numbers,
# which are nice and short
solitary @@HOME@@ /usr/X11R6/bin/xterm -geometry 80x34+0+0 -title pa -e '/usr/local/bin/zsh -l'
solitary @@HOME@@ /usr/X11R6/bin/xterm -geometry 80x34-0+0 -title re -e '/home/jmates/usr/bin/tmn re'
solitary @@HOME@@ /usr/X11R6/bin/xterm -geometry 80x24-0-0 -title ci -e '/home/jmates/usr/bin/tmn ci'
solitary @@HOME@@ /usr/X11R6/bin/xterm -geometry 80x24+0-0 -title vo -e '/usr/local/bin/zsh -l'
